---
- name: Cleanup rke
  include_tasks: rke-cleanup.yml
  tags: [ never, cleanup ]

- name: Cleanup other kubernetes-engines
  include_role:
    name: "{{ item }}"
    apply:
      tags:
        - cleanup
  with_items:
    - kube_02_install_k3s
    - kube_02_install_k8s
    - kube_02_install_minikube
  tags: [ nocleanup ]

- name: Download rke
  include_tasks: rke-download.yml
  when: 
    - serveNet_ip is defined
    - kubernetes_engine == "rke"
  tags: [ download ]

- name: Create rke-users
  include_tasks: rke-create_user.yml
  when: 
    - k8s_node in [ "install_master", "become_master", "node" ]
    - serveNet_ip is defined
    - kubernetes_engine == "rke"

- name: Download rke-binary
  include_tasks: rke-download.yml
  when: 
    - k8s_node in [ "install_master", "become_master", "node" ]
    - serveNet_ip is defined
    - kubernetes_engine == "rke"

- name: Generate rke-config-file
  include_tasks: rke-create_config.yml
  when: 
    - k8s_node in [ "install_master", "become_master", "node" ]
    - serveNet_ip is defined
    - kubernetes_engine == "rke"