---
- name: Check if rke_linux-amd64 exitst
  local_action: stat path="{{ inventory_dir }}/dynamic_vars/files/download/rke/{{ rke.version }}/rke_linux-amd64"
  run_once: true
  become: no
  register: file_adm64

- name: Check if rke_linux-arm64 exitst
  local_action: stat path="{{ inventory_dir }}/dynamic_vars/files/download/rke/{{ rke.version }}/rke_linux-arm64"
  run_once: true
  become: no
  register: file_arm64

- name: Check if rke_linux-arm exitst
  local_action: stat path="{{ inventory_dir }}/dynamic_vars/files/download/rke/{{ rke.version }}/rke_linux-arm"
  run_once: true
  become: no
  register: file_arm

- name: Downloading newest rke binaries locally
  local_action: get_url url="{{ item }}" dest="{{ inventory_dir }}/dynamic_vars/files/download/rke/{{ rke.version }}"
  run_once: true
  become: no
  with_items: 
    - https://github.com/rancher/rke/releases/download/{{ rke.version }}/rke_linux-amd64
    - https://github.com/rancher/rke/releases/download/{{ rke.version }}/rke_linux-arm64
    - https://github.com/rancher/rke/releases/download/{{ rke.version }}/rke_linux-arm
  when:
    - (not file_adm64.stat.exists) or (not file_arm64.stat.exists) or (not file_arm.stat.exists)